### ISSUE TITLE
Still showing torch.cuda.is_available() is False.

### ISSUE THREAD

**Issue by minli1004** [vt-vl-lab/3d-photo-inpainting#20]
That's really a spectacular work! 

I was trying running it on my mac 10.13.6 on terminal. Everything in the prerequisite is fine except that 
`conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit==10.1.243 -c pytorch
`
did not work. But I searched the cudatoolkit on anacadona.org and installed it following the instruction [there](https://anaconda.org/conda-forge/cudatoolkit-dev), so I think everything should be ready.

But when I tried to run the main file, it gives me this error: 
`  File "/Users/Meana/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/serialization.py", line 116, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
  0%|  ` 

I checked that the device is indeed CPU. I also checked that networkx  is 2.3. Do you have an idea why this still happens?

**Comment by minli1004** [comment]
Please ignore this. I did not read this [ticket](https://github.com/vt-vl-lab/3d-photo-inpainting/issues/3) carefully. I set gpu_ids : -1 in argument.yml and issue solved. Sorry for bothering.
